### ISSUE TITLE
Why separate the scripts from the prefixes

### ISSUE THREAD

**Issue by kpu** [bitextor/nonbreaking_prefixes#1]
Can I ask why you have the scripts scattered between https://github.com/bitextor/bitextor/tree/master/utils and https://github.com/bitextor/bitextor/tree/master/zipporah while the data they need is in this repo?  It's not as though anybody will find it useful to have nonbreaking_prefixes in isolation from the scripts that use them.

**Comment by Lesbinary** [comment]
You are right. In fact, I will use the https://github.com/kpu/preprocess instead for all those scripts in Bitextor repo as soon as possible.
